---

name: "PR Title Check Workflow"

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr_title_check:
    runs-on: ubuntu-latest
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
    steps:
      - name: PR Title Check ✅  # 👈 this is what shows in branch protection
        run: |
          echo "PR Title: $PR_TITLE"
          #shopt -s nocasematch  # ✅ Allow case-insensitive matching
          if [[ ! "$PR_TITLE" =~ ^([Ff]eat|[Ff]ix|[Cc]hore|[Dd]ocs|[S]style|[Rr]efactor|[Tt]est|[Pp]erf)(\(.+\))?:\ .+ ]]; then
            echo "::error::❌ PR title must follow Conventional Commit format, e.g., 'feat(ui): add login button'"
            echo ""
            echo "🔧 Allowed types and their meanings:"
            echo "  - feat:     A new feature"
            echo "  - fix:      A bug fix"
            echo "  - chore:    Routine tasks like build process or config"
            echo "  - docs:     Documentation only changes"
            echo "  - style:    Code style changes (formatting, lint, etc.)"
            echo "  - refactor: Code changes without fixing bugs or adding features"
            echo "  - test:     Adding or updating tests"
            echo "  - perf:     Performance improvements"
            exit 1
          fi
